server:
  servlet:
    encoding:
      charser: utf-8
      force: true
  port: 8080

logging:
  level:
    root: INFO # 모든 라이브러리는 INFO 이상만 출력
    com.tenco: DEBUG # 내 프로젝트는 디버그 이상 모두 출력

spring:
  #데이터베이스 연결 설정 (MySQL)
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=Asia/Seoul
#    username: root
#    password: root
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true

#      초기 데이터 설정 h2 내장 메모리 즉 서버가 꺼지면 안의 데이터가 날아간다 그래서 data.sql로 파일을 만들어서 저장하는거임
# 이거 설정한 순서 먼저 실행되기에 Board에서 테이블을 만들어줘도 설정 먼저 진행되기에 데이터를 못넣은거임
  sql:
    init:
      data-locations:
        - classpath:db/data.sql

  jpa:
    hibernate:
      # credate 애플리케이션 시작시 테이블 새로 생성 ddl 데이터 정의
      # 기존 데티터는 모두 삭제됨 (개발용)
      ddl-auto: create
      # 자동으로 만들어주는 SQL 쿼리를 콘솔에 출력 (개발용)
    show-sql: true
    properties:
      hibernate:
        # SQL 쿼리를 보기좋게 포멧팅
        format_sql: true

    # data.sql 파일을 하이버네이트 초기화 이후에 실행
    # 클래스로 데이터 베이스 만드는것 먼저 실행후에 실행해라
    defer-datasource-initialization: true